version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  library-api:
    build: .
    container_name: library-api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pgdata:
